namespace BookShelfWeb.MockData
{
    public static class BookMockCatalog
    {
        public static IReadOnlyList<BookCatalogEntry> Books { get; } =
        [
            new() { Title = "The Glass Harbor", Author = "Elena Maris", ISBN = "9781736102101", CategoryName = "Fiction", ImageUrl = "/images/mock-covers/the-glass-harbor.svg", ShortDescription = "A layered family novel set in a fading Adriatic port city.", Description = "<p>When Ana returns to her childhood harbor town to settle her father's estate, she discovers a ledger that quietly rewrites everything her family believed about its past.</p><p>Part literary drama and part generational mystery, the novel follows three siblings as they choose between inheritance, reinvention, and truth.</p>", ListPrice = 26.99, Price = 21.99, Price50 = 19.99, Price100 = 17.99, PublishedYear = 2022, PageCount = 368, Publisher = "Blue Quay Press", AverageRating = 4.6, ReviewCount = 412, StockCount = 34, IsFeatured = true, IsDiscounted = true, UnitsSold = 1280, AddedOnUtc = new DateTime(2026, 2, 12, 0, 0, 0, DateTimeKind.Utc), Tags = ["family saga", "coastal fiction", "book club"] },
            new() { Title = "Lanterns of Alder Keep", Author = "Mira Solis", ISBN = "9781736102102", CategoryName = "Fantasy", ImageUrl = "/images/mock-covers/lanterns-of-alder-keep.svg", ShortDescription = "A luminous castle fantasy about guardians, secrets, and old magic.", Description = "<p>Every winter, the lantern wardens of Alder Keep climb the northern towers to keep the mountain spirits asleep.</p><p>When apprentice Iven lights the wrong flame, she awakens a buried pact that could save the kingdom or unmake it by spring.</p>", ListPrice = 29.99, Price = 24.99, Price50 = 22.99, Price100 = 20.99, PublishedYear = 2024, PageCount = 432, Publisher = "Moonbridge Books", AverageRating = 4.8, ReviewCount = 931, StockCount = 42, IsFeatured = true, IsBestseller = true, IsNewRelease = true, IsDiscounted = true, UnitsSold = 3420, AddedOnUtc = new DateTime(2026, 6, 3, 0, 0, 0, DateTimeKind.Utc), Tags = ["epic fantasy", "slow burn", "found family"] },
            new() { Title = "The Cartographer's Secret", Author = "Nolan Price", ISBN = "9781736102103", CategoryName = "Mystery", ImageUrl = "/images/mock-covers/the-cartographers-secret.svg", ShortDescription = "A puzzle-box mystery that begins with a map no one remembers drawing.", Description = "<p>Archivist Leo Varga finds an unsigned city map in a sealed museum drawer, complete with streets that do not exist and one address that points to his own apartment.</p><p>Each clue draws him deeper into a decades-old disappearance hidden under layers of civic mythology.</p>", ListPrice = 25.99, Price = 22.99, Price50 = 20.99, Price100 = 18.99, PublishedYear = 2021, PageCount = 344, Publisher = "Northline Crime", AverageRating = 4.5, ReviewCount = 688, StockCount = 17, IsFeatured = true, IsBestseller = true, UnitsSold = 2890, AddedOnUtc = new DateTime(2025, 11, 10, 0, 0, 0, DateTimeKind.Utc), Tags = ["literary mystery", "urban noir", "twisty"] },
            new() { Title = "Winter at Bellweather Inn", Author = "Sophie Vale", ISBN = "9781736102104", CategoryName = "Romance", ImageUrl = "/images/mock-covers/winter-at-bellweather-inn.svg", ShortDescription = "A cozy romance set in a snowbound inn on the Irish coast.", Description = "<p>Interior stylist Maeve takes a six-week contract to restore a weather-beaten inn before its grand reopening.</p><p>Between sea storms, late-night repairs, and a quietly irresistible chef, she finds the kind of second chance that asks to be built slowly and kept for good.</p>", ListPrice = 19.99, Price = 16.99, Price50 = 15.49, Price100 = 13.99, PublishedYear = 2023, PageCount = 312, Publisher = "Silver Birch Romance", AverageRating = 4.4, ReviewCount = 521, StockCount = 29, IsDiscounted = true, UnitsSold = 1760, AddedOnUtc = new DateTime(2026, 1, 8, 0, 0, 0, DateTimeKind.Utc), Tags = ["cozy romance", "small town", "winter read"] },
            new() { Title = "Orbiting Cassandra", Author = "J. R. Kellan", ISBN = "9781736102105", CategoryName = "Science Fiction", ImageUrl = "/images/mock-covers/orbiting-cassandra.svg", ShortDescription = "A near-future space drama about memory, loyalty, and first contact.", Description = "<p>On a research station circling Saturn's moon Phoebe, communications specialist Cassandra Hale intercepts a signal that seems to answer questions humanity never learned how to ask.</p><p>The discovery fractures the crew into factions and forces her to decide whether survival matters more than truth.</p>", ListPrice = 28.99, Price = 23.99, Price50 = 21.99, Price100 = 19.99, PublishedYear = 2025, PageCount = 416, Publisher = "Helix Horizon", AverageRating = 4.7, ReviewCount = 804, StockCount = 21, IsFeatured = true, IsNewRelease = true, IsDiscounted = true, UnitsSold = 3015, AddedOnUtc = new DateTime(2026, 5, 18, 0, 0, 0, DateTimeKind.Utc), Tags = ["space opera", "first contact", "high stakes"] },
            new() { Title = "Red Clay and Rain", Author = "Thomas Adebayo", ISBN = "9781736102106", CategoryName = "History", ImageUrl = "/images/mock-covers/red-clay-and-rain.svg", ShortDescription = "A vivid history of rail, labor, and transformation across West Africa.", Description = "<p>Historian Thomas Adebayo traces how rail corridors reshaped local economies, migration patterns, and political imagination across three generations.</p><p>Blending archival sources with oral histories, the book turns infrastructure into a deeply human story.</p>", ListPrice = 31.99, Price = 27.99, Price50 = 25.99, Price100 = 23.99, PublishedYear = 2020, PageCount = 390, Publisher = "Fieldstone History", AverageRating = 4.3, ReviewCount = 214, StockCount = 14, UnitsSold = 890, AddedOnUtc = new DateTime(2025, 9, 21, 0, 0, 0, DateTimeKind.Utc), Tags = ["world history", "transport", "social history"] },
            new() { Title = "The Listening Brain", Author = "Dr. Mira Weston", ISBN = "9781736102107", CategoryName = "Psychology", ImageUrl = "/images/mock-covers/the-listening-brain.svg", ShortDescription = "An accessible psychology title about attention, empathy, and better conversations.", Description = "<p>Why do some conversations leave us energized while others feel like static? Clinical psychologist Dr. Mira Weston explains how attention, bias, and emotional regulation shape the way we hear one another.</p><p>The result is practical, research-backed, and surprisingly warm.</p>", ListPrice = 24.99, Price = 20.99, Price50 = 18.99, Price100 = 16.99, PublishedYear = 2024, PageCount = 288, Publisher = "North Atlas Press", AverageRating = 4.6, ReviewCount = 463, StockCount = 38, IsBestseller = true, IsDiscounted = true, UnitsSold = 2544, AddedOnUtc = new DateTime(2026, 3, 15, 0, 0, 0, DateTimeKind.Utc), Tags = ["self development", "communication", "behavioral science"] },
            new() { Title = "Founder at Dawn", Author = "Luca Mercer", ISBN = "9781736102108", CategoryName = "Business", ImageUrl = "/images/mock-covers/founder-at-dawn.svg", ShortDescription = "A grounded startup book focused on discipline, cash flow, and sustainable growth.", Description = "<p>Built from interviews with founders who survived their first five years, this book rejects hype in favor of operating rhythm, sales clarity, and calm decision-making.</p><p>It is especially useful for small teams trying to scale without breaking themselves.</p>", ListPrice = 27.99, Price = 23.49, Price50 = 21.49, Price100 = 19.49, PublishedYear = 2022, PageCount = 304, Publisher = "Ledger House", AverageRating = 4.5, ReviewCount = 342, StockCount = 26, IsBestseller = true, IsDiscounted = true, UnitsSold = 2130, AddedOnUtc = new DateTime(2025, 12, 2, 0, 0, 0, DateTimeKind.Utc), Tags = ["startups", "leadership", "operations"] },
            new() { Title = "Practical Clean Code", Author = "Mina Kovac", ISBN = "9781736102109", CategoryName = "Programming", ImageUrl = "/images/mock-covers/practical-clean-code.svg", ShortDescription = "A modern programming guide on maintainability, naming, tests, and review habits.", Description = "<p>Instead of abstract rules, Mina Kovac walks through real-world refactors, showing how teams reduce cognitive load one decision at a time.</p><p>Examples center on service boundaries, naming, test strategy, and the social side of code quality.</p>", ListPrice = 39.99, Price = 32.99, Price50 = 29.99, Price100 = 26.99, PublishedYear = 2025, PageCount = 520, Publisher = "Stack River Publishing", AverageRating = 4.9, ReviewCount = 1184, StockCount = 19, IsFeatured = true, IsBestseller = true, IsNewRelease = true, IsDiscounted = true, UnitsSold = 4170, AddedOnUtc = new DateTime(2026, 6, 22, 0, 0, 0, DateTimeKind.Utc), Tags = ["software engineering", "refactoring", "team practices"] },
            new() { Title = "The Archivist of Broken Clocks", Author = "Selene Ward", ISBN = "9781736102110", CategoryName = "Fiction", ImageUrl = "/images/mock-covers/the-archivist-of-broken-clocks.svg", ShortDescription = "A melancholic contemporary novel about repair, grief, and time.", Description = "<p>In a city where every district keeps time differently, an archivist cataloging discarded clocks begins to suspect that one of them is still measuring the life of someone she lost.</p><p>Elegant and quiet, the novel explores how ritual can become a way back into the world.</p>", ListPrice = 24.99, Price = 20.99, Price50 = 18.99, Price100 = 16.99, PublishedYear = 2021, PageCount = 336, Publisher = "Blue Quay Press", AverageRating = 4.4, ReviewCount = 267, StockCount = 12, IsDiscounted = true, UnitsSold = 990, AddedOnUtc = new DateTime(2025, 10, 12, 0, 0, 0, DateTimeKind.Utc), Tags = ["literary fiction", "grief", "atmospheric"] },
            new() { Title = "The Quiet Arithmetic of Memory", Author = "Helena Pryce", ISBN = "9781736102111", CategoryName = "Biography", ImageUrl = "/images/mock-covers/the-quiet-arithmetic-of-memory.svg", ShortDescription = "A reflective biography of a mathematician who changed public education.", Description = "<p>This biography follows Vera Markovic from wartime classrooms to national reform, showing how a fiercely private thinker became an unlikely public architect of change.</p><p>It is intimate, restrained, and rich with intellectual history.</p>", ListPrice = 30.99, Price = 26.49, Price50 = 24.49, Price100 = 22.49, PublishedYear = 2023, PageCount = 372, Publisher = "North Atlas Press", AverageRating = 4.2, ReviewCount = 198, StockCount = 16, UnitsSold = 740, AddedOnUtc = new DateTime(2026, 1, 30, 0, 0, 0, DateTimeKind.Utc), Tags = ["biography", "education", "science history"] },
            new() { Title = "The Fourth Signal", Author = "Arman Leigh", ISBN = "9781736102112", CategoryName = "Science Fiction", ImageUrl = "/images/mock-covers/the-fourth-signal.svg", ShortDescription = "A sleek sci-fi thriller about encrypted broadcasts and synthetic diplomacy.", Description = "<p>On the eve of a fragile peace summit, a translator trained on machine consciousness receives a fourth diplomatic signal no one else can decode.</p><p>What starts as an intelligence puzzle becomes a race to prevent a war triggered by a misunderstanding neither side intended.</p>", ListPrice = 27.99, Price = 22.99, Price50 = 20.99, Price100 = 18.99, PublishedYear = 2026, PageCount = 384, Publisher = "Helix Horizon", AverageRating = 4.7, ReviewCount = 276, StockCount = 33, IsNewRelease = true, IsDiscounted = true, UnitsSold = 1495, AddedOnUtc = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc), Tags = ["tech thriller", "aliens", "diplomacy"] },
            new() { Title = "Letters from Marigold Lane", Author = "Clara Bennett", ISBN = "9781736102113", CategoryName = "Romance", ImageUrl = "/images/mock-covers/letters-from-marigold-lane.svg", ShortDescription = "An epistolary romance about neighbors, grief, and handwritten courage.", Description = "<p>Two people on the same London street begin leaving anonymous notes in a communal mailbox, each believing the other is simply a kind stranger.</p><p>The correspondence becomes a lifeline, then a love story, before either of them knows who has been listening so carefully.</p>", ListPrice = 18.99, Price = 15.99, Price50 = 14.49, Price100 = 12.99, PublishedYear = 2025, PageCount = 296, Publisher = "Silver Birch Romance", AverageRating = 4.6, ReviewCount = 602, StockCount = 24, IsFeatured = true, IsBestseller = true, UnitsSold = 2301, AddedOnUtc = new DateTime(2026, 4, 9, 0, 0, 0, DateTimeKind.Utc), Tags = ["epistolary", "neighbors to lovers", "feel good"] },
            new() { Title = "Patterns for Resilient Systems", Author = "Devon Hale", ISBN = "9781736102114", CategoryName = "Programming", ImageUrl = "/images/mock-covers/patterns-for-resilient-systems.svg", ShortDescription = "A practical architecture book on reliability, observability, and failure design.", Description = "<p>Devon Hale shows how strong software systems are designed around interruption, not ideal conditions.</p><p>With examples from distributed platforms and smaller product teams, the book keeps architecture tangible and immediately useful.</p>", ListPrice = 42.99, Price = 35.99, Price50 = 32.99, Price100 = 29.99, PublishedYear = 2024, PageCount = 548, Publisher = "Stack River Publishing", AverageRating = 4.8, ReviewCount = 852, StockCount = 11, IsFeatured = true, IsBestseller = true, UnitsSold = 3910, AddedOnUtc = new DateTime(2026, 2, 5, 0, 0, 0, DateTimeKind.Utc), Tags = ["architecture", "distributed systems", "backend"] },
            new() { Title = "The River Between Wars", Author = "Iris Petrov", ISBN = "9781736102115", CategoryName = "History", ImageUrl = "/images/mock-covers/the-river-between-wars.svg", ShortDescription = "A narrative history of a border river that shaped diplomacy and daily life.", Description = "<p>Using diaries, trade records, and military dispatches, Iris Petrov reconstructs how a single river served as frontier, refuge, and marketplace across two unstable decades.</p><p>The result reads with the pace of narrative nonfiction and the texture of lived experience.</p>", ListPrice = 32.99, Price = 27.99, Price50 = 25.99, Price100 = 23.99, PublishedYear = 2021, PageCount = 408, Publisher = "Fieldstone History", AverageRating = 4.4, ReviewCount = 287, StockCount = 13, UnitsSold = 1040, AddedOnUtc = new DateTime(2025, 8, 27, 0, 0, 0, DateTimeKind.Utc), Tags = ["european history", "narrative nonfiction", "borders"] },
            new() { Title = "Houses of Salt and Snow", Author = "Aveline Roe", ISBN = "9781736102116", CategoryName = "Fantasy", ImageUrl = "/images/mock-covers/houses-of-salt-and-snow.svg", ShortDescription = "A gothic fantasy of rival houses and weather-bound magic.", Description = "<p>On an island where each ruling house commands a different season, a young envoy from the salt coast is sent to negotiate a marriage treaty and finds the dead still advising the living.</p><p>The novel balances court intrigue, winter atmospherics, and lyrical worldbuilding.</p>", ListPrice = 30.99, Price = 25.99, Price50 = 23.99, Price100 = 21.99, PublishedYear = 2026, PageCount = 448, Publisher = "Moonbridge Books", AverageRating = 4.7, ReviewCount = 351, StockCount = 36, IsNewRelease = true, IsFeatured = true, IsDiscounted = true, UnitsSold = 1712, AddedOnUtc = new DateTime(2026, 6, 12, 0, 0, 0, DateTimeKind.Utc), Tags = ["gothic fantasy", "court intrigue", "atmospheric"] },
            new() { Title = "The Investor's Compass", Author = "Rachel Sung", ISBN = "9781736102117", CategoryName = "Business", ImageUrl = "/images/mock-covers/the-investors-compass.svg", ShortDescription = "A calm guide to long-term investing for first-generation wealth builders.", Description = "<p>Rachel Sung translates portfolio theory, risk, and behavioral traps into language ordinary readers can use without feeling talked down to.</p><p>It is especially strong on building a repeatable decision process instead of chasing market noise.</p>", ListPrice = 23.99, Price = 19.99, Price50 = 17.99, Price100 = 15.99, PublishedYear = 2023, PageCount = 280, Publisher = "Ledger House", AverageRating = 4.5, ReviewCount = 410, StockCount = 41, IsBestseller = true, IsDiscounted = true, UnitsSold = 2625, AddedOnUtc = new DateTime(2026, 3, 2, 0, 0, 0, DateTimeKind.Utc), Tags = ["finance", "personal investing", "decision making"] },
            new() { Title = "The Last Mapmaker's Daughter", Author = "Rina Calder", ISBN = "9781736102118", CategoryName = "Mystery", ImageUrl = "/images/mock-covers/the-last-mapmakers-daughter.svg", ShortDescription = "A literary mystery tracing a vanished atlas and a missing father.", Description = "<p>When Mara receives a parcel containing her father's drafting compass twenty years after he disappeared, she follows its markings across ports, archives, and old rivalries.</p><p>The investigation unfolds as much through geography as through grief.</p>", ListPrice = 26.49, Price = 21.99, Price50 = 19.99, Price100 = 17.99, PublishedYear = 2024, PageCount = 352, Publisher = "Northline Crime", AverageRating = 4.6, ReviewCount = 534, StockCount = 18, IsFeatured = true, IsDiscounted = true, UnitsSold = 1844, AddedOnUtc = new DateTime(2026, 5, 6, 0, 0, 0, DateTimeKind.Utc), Tags = ["family mystery", "travel", "slow burn suspense"] }
        ];

        public static IReadOnlyList<string> WishlistIsbns { get; } =
        [
            "9781736102102",
            "9781736102109",
            "9781736102113",
            "9781736102116"
        ];

        public static IReadOnlyDictionary<string, int> CartIsbnsWithCounts { get; } =
            new Dictionary<string, int>
            {
                ["9781736102109"] = 1,
                ["9781736102102"] = 2,
                ["9781736102105"] = 1
            };
    }
}
